version: '3'
services:
  terraria:
    build: ./
    volumes:
      - ./config:/etc/Terraria
      - ./worlds:/usr/local/games/Terraria/Worlds
    ports: 
      - 7777:7777
    environment: 
      - WORLD=<<WORLD_NAME>>
      - MAX_PLAYERS=10
      - PORT=7777
      - PASSWORD_FILE=server_password.txt
      - MOTD="Welcome, fuckers! Enjoy your stay and try not to die..."
      - SECURE=0 
      - LANGUAGE=de\/DE
      - AUTOSAVE_INTERVAL=5m
      - START_PARAMETER="-steam"
    stop_signal: SIGTERM
    restart: unless-stopped
